### PR TITLE
Dynamic Payload Size Support

### LINKED ISSUE #44: qemu: Add support for dynamic payload size for packets
Make complementary changes for #28 on QEMU.

### LINKED ISSUE #49: core: Fix incorrect payload length for payloads
Sometimes the payload length is smaller than the payload, which could corrupt reading further packets from the QEMU side.

### PR DESCRIPTION
**Pull request by zhxq**
This commit brings support to dynamic payload size corresponding to the change in the Core side (see https://github.com/opencxl/opencxl-core/pull/29). 

This commit also brings support to config space read/write handling on the Core side (see https://github.com/opencxl/opencxl-core/pull/37). 

QEMU will fail to boot up without this commit when using OpenCXL core with those two core-side commits.

Signed-off-by: Xiangqun Zhang <xzhang84@syr.edu>

### CODE REVIEW

File: include/hw/cxl/cxl_emulator_packet.h [hunk 1]
```diff
@@ -365,28 +379,28 @@ typedef struct {
     cache_req_h2d_opcode_t opcode : 3;
     uint64_t addr                 : 46;
     uint16_t uq_id                : 12;
-    uint8_t cache_id              : 4;
-    uint8_t rsvd                  : 6;
+    uint16_t cache_id             : 4;
+    uint16_t rsvd                 : 6;
```
Comment (kyeyoon-eeum) [inline include/hw/cxl/cxl_emulator_packet.h:379]: What's the reason for this (and below similar) type changes?

File: hw/pci-bridge/cxl_root_port.c [hunk 2]
```diff
@@ -310,6 +309,18 @@ void cxl_remote_config_space_read(PCIDevice *d, uint16_t bdf, uint32_t offset,
 
     wait_for_cxl_io_cfg_completion(crp->socket_fd, tag, val);
 
+    /*
+    Since now the OpenCXL backend assumes 4-byte aligned data reqs,
+    We are going to make sure that we can read the data correctly
+    from correct locations. Similar to CxlIoCfgWrPacket.get_value().
+    */
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_root_port.c]:
```
/*
 * Since now the OpenCXL backend assumes 4-byte aligned data reqs,
 * are going to make sure that we can read the data correctly
 * from correct locations. Similar to CxlIoCfgWrPacket.get_value().
 */
```

File: hw/pci-bridge/cxl_socket_transport.c [hunk 3]
```diff
@@ -354,30 +354,51 @@ bool send_cxl_io_mem_write(int socket_fd, hwaddr hpa, uint64_t val, int size,
...
 
-    packet.system_header.payload_type = CXL_IO;
-    packet.system_header.payload_length = sizeof(packet);
+    uint16_t hdr_length = round_up_to_nearest_dword(size) / 4;
 
-    packet.cxl_io_header.fmt_type = MWR_64B;
-    uint16_t hdr_length = round_up_to_nearest_dword(size);
-    packet.cxl_io_header.length_upper = EXTRACT_UPPER_2(hdr_length);
-    packet.cxl_io_header.length_lower = EXTRACT_LOWER_8(hdr_length);
+    if (size > 4) {
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]:
```
if (size == 4) {

} else if (size == 8) {

} else {
  /* error */
}
```

File: hw/pci-bridge/cxl_socket_transport.c [hunk 4]
```diff
@@ -354,30 +354,51 @@ bool send_cxl_io_mem_write(int socket_fd, hwaddr hpa, uint64_t val, int size,
...
+        assert(size == 8);
+        assert(val < 0xFFFFFFFFFFFFFFFF);
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]: Use constants from `limits.h`.

File: hw/pci-bridge/cxl_socket_transport.c [hunk 5]
```diff
@@ -319,20 +319,20 @@ bool send_cxl_io_mem_read(int socket_fd, hwaddr hpa, int size, uint16_t *tag)
...
     packet.mreq_header.tag = *tag;
 
-    hpa = htonll(hpa);
+    packet.mreq_header.addr_lower = (hpa & 0xFF) >> 2;
 
-    packet.mreq_header.addr_upper =
-        (hpa >> 8) & 0xFFFFFFFFFFFFFF; 
-    packet.mreq_header.addr_lower = (hpa & 0xFF) >> 2; 
+    /* No need to do >> 8 because htonll reverts the byte order
+       and the mask removes the MSByte (was LSByte) automatically. */
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]:
```
/*
 * No need to do >> 8 because htonll reverts the byte order
 * and the mask removes the MSByte (was LSByte) automatically.
 */
```

File: hw/pci-bridge/cxl_socket_transport.c [hunk 6]
```diff
@@ -354,30 +354,51 @@ bool send_cxl_io_mem_write(int socket_fd, hwaddr hpa, uint64_t val, int size,
...
+        packet.mreq_header.req_id = 0;
+        packet.mreq_header.tag = *tag;
+
+        packet.mreq_header.addr_lower = (hpa & 0xFF) >> 2;
+        packet.mreq_header.addr_upper = htonll(hpa) & 0xFFFFFFFFFFFFFF;
+        packet.system_header.payload_length = sizeof(packet);
+        packet.data = (uint32_t)(val & 0xFFFFFFFF);
+        successful = write(socket_fd, &packet, sizeof(packet)) != -1;
+        trace_cxl_socket_debug_num("MWR_32B Packet Size", sizeof(packet));
+    }
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]: Use a pointer to assign common fields, then use if/else-if statement to assign non-common fields.

File: hw/pci-bridge/cxl_socket_transport.c [hunk 7]
```diff
@@ -513,24 +534,27 @@ cxl_io_completion_packet_t *wait_for_cxl_io_completion(int socket_fd,
...
 
-cxl_io_completion_data_packet_t *wait_for_cxl_io_completion_data(int socket_fd,
-                                                                 uint16_t tag)
+uint64_t wait_for_cxl_io_completion_data(int socket_fd, uint16_t tag,
+                                         uint64_t *data)
 {
     trace_cxl_socket_debug_msg("[Receiving Packet] START");
 
-    cxl_io_completion_data_packet_t *packet = NULL;
+    uint64_t packet_size = 0;
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]: Change to `size_t`. Since:
```
typedef struct packet_table_entry {
    ...
    size_t packet_size;
} packet_table_entry_t;
```

File: hw/pci-bridge/cxl_socket_transport.c [hunk 8]
```diff
@@ -558,16 +582,16 @@ void wait_for_cxl_io_cfg_completion(int socket_fd, uint16_t tag, uint32_t *data)
                 assert(entry->packet_size ==
                            sizeof(cxl_io_completion_packet_t) ||
                        entry->packet_size ==
-                           sizeof(cxl_io_completion_data_packet_t));
+                           sizeof(cxl_io_completion_data_packet_32b_t));
             }
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c:574]: It would never be `cxl_io_completion_data_packet_64b_t`?

File: hw/pci-bridge/cxl_socket_transport.c [hunk 9]
```diff
@@ -354,30 +354,51 @@ bool send_cxl_io_mem_write(int socket_fd, hwaddr hpa, uint64_t val, int size,
 
     assert(size % 4 == 0); // Ensure size is dword aligned
 
-    cxl_io_mem_wr_packet_t packet;
+    cxl_io_mem_wr_packet_32b_t packet;
+    cxl_io_mem_wr_packet_64b_t packet_64;
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]: `packet` -> `packet_32`

**Review by kyeyoon-eeum — CHANGES_REQUESTED** [review]

File: include/hw/cxl/cxl_emulator_packet.h (hunk 1 above)
Comment (zhxq) [reply include/hw/cxl/cxl_emulator_packet.h:379]: This is to fix the compiler warnings we talked about last time.

File: hw/pci-bridge/cxl_root_port.c (hunk 2 above)
Comment (zhxq) [reply hw/pci-bridge/cxl_root_port.c]: Will remove.

File: hw/pci-bridge/cxl_socket_transport.c (hunk 6 above)
Comment (zhxq) [reply hw/pci-bridge/cxl_socket_transport.c]: That was what I wanted to do, but `packet32` and `packet64` are of different types. A common pointer to assign values may cause issues. I still need to add extra code for type casting one type to the other, which will result in similar number of lines. This would be easier if the code is C++ (we can use templates then). 

I also tried memcpy `packet32` to `packet64` and change some values, but it would cause packet corruption.

File: hw/pci-bridge/cxl_socket_transport.c (hunk 8 above)
Comment (zhxq) [reply hw/pci-bridge/cxl_socket_transport.c:574]: Yes. In fact, the function and the call stack ask for a 32-bit integer.

File: hw/pci-bridge/cxl_socket_transport.c (hunk 6 above)
Comment (kyeyoon-eeum) [reply hw/pci-bridge/cxl_socket_transport.c]: Temporarily cast it to a header-only type to assign the fields. e.g.
```
typedef struct {
    system_header_packet_t system_header;
    cxl_io_header_t cxl_io_header;
    cxl_io_mreq_header_t mreq_header;
} __attribute__((packed)) cxl_io_mem_packet_t;
```
I see 6 (or more) lines of code that could be shared.

Condition-based value determination followed by common "assignment code" could be useful here as well.

File: hw/pci-bridge/cxl_socket_transport.c [hunk 10]
```diff
@@ -354,31 +351,44 @@ bool send_cxl_io_mem_write(int socket_fd, hwaddr hpa, uint64_t val, int size,
...
+    cxl_io_mem_base_packet_t *base;
+    cxl_io_mem_wr_packet_32b_t packet_32;
+    cxl_io_mem_wr_packet_64b_t packet_64;
+    bool successful;
+
+    uint16_t hdr_length = round_up_to_nearest_dword(size) / 4;
+    size_t payload_length = 0;
+
+    if (size == 8) {
+        assert(val < UINT64_MAX);
```
Comment (kyeyoon-eeum) [inline hw/pci-bridge/cxl_socket_transport.c]: Thinking of it, this is actually a meaningless check (i.e. always true) because (UINT64_MAX + 1) is not greater than UINT64_MAX on a uint64_t variable due to overflow.

Remove.

**Review by kyeyoon-eeum — CHANGES_REQUESTED** [review]

**Review by kyeyoon-eeum — APPROVED** [review]
